[tools]
go = "latest"
gofumpt = "latest"
golangci-lint = "latest"
pre-commit = "latest"

[tasks.init]
description = "Install hooks and setup environment"
run = "pre-commit install"

[tasks.pre-commit]
description = "Run pre-commit"
run = "pre-commit run --all-files"

[tasks.fmt]
description = "Format Go files"
quiet = true
usage = """
arg "<path>" help="path to run the formatter on"
flag "-w --write" help="Write result to (source) files instead of stdout"
flag "-d --diff"  help="Display diffs instead of rewriting files"
"""
run = """
if [ "$usage_write" = "true" ]; then
  gofumpt -w ${usage_path}
elif [ "$usage_diff" = "true" ]; then
  gofumpt -d ${usage_path}
else
  gofumpt ${usage_path}
fi
"""

[tasks.lint]
description = "Lint Go files"
quiet = true
run = "golangci-lint run"

